stages:
  fetch_data:
    cmd: python delivery_delay_prediction/dataset.py
    deps:
      - delivery_delay_prediction/dataset.py
      - delivery_delay_prediction/config.py
      - sql/feature_queries.sql
    outs:
      - data/interim/analytical_dataset.csv
  
  engineer_features:
    cmd: python delivery_delay_prediction/features.py
    deps:
      - data/interim/analytical_dataset.csv
      - delivery_delay_prediction/features.py
      - delivery_delay_prediction/config.py
    outs:
      - data/processed/features.csv
  
  train_model:
    cmd: python delivery_delay_prediction/train.py
    deps:
      - data/processed/features.csv
      - delivery_delay_prediction/train.py
      - delivery_delay_prediction/features.py
      - delivery_delay_prediction/config.py
    outs:
      - models/catboost_baseline.cbm
  
  tune_catboost:
    cmd: python delivery_delay_prediction/modeling/tune_catboost.py --n-trials 50
    deps:
      - data/processed/features.csv
      - delivery_delay_prediction/modeling/tune_catboost.py
    outs:
      - models/catboost_tuned.cbm

  train_lightgbm:
    cmd: python delivery_delay_prediction/modeling/train_lightgbm.py
    deps:
      - data/processed/features.csv
      - delivery_delay_prediction/modeling/train_lightgbm.py
    outs:
      - models/lightgbm_baseline.txt

  tune_lightgbm:
    cmd: python delivery_delay_prediction/modeling/tune_lightgbm.py --n-trials 50
    deps:
      - data/processed/features.csv
      - delivery_delay_prediction/modeling/tune_lightgbm.py
    outs:
      - models/lightgbm_tuned.txt


  predict:
    cmd: python delivery_delay_prediction/modeling/predict.py
    deps:
      - data/processed/features.csv
      - delivery_delay_prediction/modeling/predict.py
      - models/catboost_baseline.cbm
    outs:
      - data/processed/predictions.csv
